import Navbar from "@/components/Navbar";
import AuthProvider from "@/components/provider/authProvider";
import dbConnectMongo from "@/dbConnect/mongo";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnectMongo()
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <Navbar />
        <main className="py-8">
          {children}
        </main>
        </AuthProvider>
      </body>
    </html>
  );
}
